name: Jonathan Kim
tagline: Designing myself for startups.
baseurl:
fqd: http://jonathan-kim.com
domain: jonathan-kim.com

exclude: ['sass', 'package.json', 'Gruntfile', 'wordpress.xml', 'generators']

pygments: true
permalink: /:year/:title/
redirects: yes
markdown: kramdown
